@startuml
'https://plantuml.com/class-diagram

interface MyQueue<T>
abstract class MyAbstractQueue<T>
class BlockingQueue<T>

MyQueue <|-- MyAbstractQueue
MyAbstractQueue <|-- BlockingQueue

MyQueue : boolean enqueue(T t)
MyQueue : T dequeue()

@enduml